# Generated by Django 3.0.4 on 2020-06-05 04:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='unique',
            field=models.UUIDField(default='adfc8d31b32b4f2b80bc37c16389e1eb', unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=tinymce.models.HTMLField(),
        ),
    ]
