# Generated by Django 2.2.13 on 2020-06-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200605_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='unique',
            field=models.UUIDField(default='366da5448c6643f2b3fcd120e1758fb3', unique=True),
        ),
    ]
